CREATE TABLE users(
    id INT NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    push_token VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE reminders(
    id INT NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(255) NOT NULL,
    pushed_on TIMESTAMP NOT NULL,
    poster_id INT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE subscribes(
    id INT NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id INT NOT NULL,
    reminder_id INT NOT NULL,
    PRIMARY KEY(id)
);
